# Generated by Django 5.2.1 on 2025-11-17 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianAvailability',
            fields=[
                ('availability_id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(max_length=255)),
                ('start_time', models.CharField(max_length=255)),
                ('end_time', models.CharField(max_length=255)),
                ('is_available', models.BooleanField()),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('experience_years', models.IntegerField(blank=True, null=True)),
                ('technician_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'TECHNICIAN_AVAILABILITY',
            },
        ),
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_type', models.CharField(max_length=255)),
                ('document_url', models.CharField(max_length=255)),
                ('upload_date', models.DateField()),
                ('verification_status', models.CharField(max_length=255)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('technician_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'VERIFICATION_DOCUMENT',
            },
        ),
        migrations.CreateModel(
            name='TechnicianSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_level', models.CharField(max_length=255)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
                ('technician_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'TECHNICIAN_SKILL',
                'unique_together': {('technician_user', 'service')},
            },
        ),
    ]
