# Generated by Django 5.2.1 on 2025-12-18 14:32

from django.conf import settings
from django.db import migrations, models


def populate_masked_pan(apps, schema_editor):
    PaymentMethod = apps.get_model('payments', 'PaymentMethod')
    seen = set()
    for pm in PaymentMethod.objects.all():
        # Fallback to '****' if last_four_digits is missing/empty
        pan = pm.last_four_digits if pm.last_four_digits else '****'
        card_type = pm.card_type
        user_id = pm.user_id
        
        identifier = (user_id, pan, card_type)
        
        if identifier in seen:
            # Duplicate detected (would violate new constraint), delete it
            pm.delete()
        else:
            seen.add(identifier)
            pm.masked_pan = pan
            pm.save(update_fields=['masked_pan'])

class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1. Drop old constraint (requires last_four_digits to exist)
        migrations.AlterUniqueTogether(
            name='paymentmethod',
            unique_together=set(),
        ),
        # 2. Add new fields
        migrations.AddField(
            model_name='paymentmethod',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='masked_pan',
            field=models.CharField(default='****', max_length=20),
        ),
        # 3. Data Migration: Copy last_four_digits -> masked_pan
        migrations.RunPython(populate_masked_pan, reverse_code=migrations.RunPython.noop),
        
        migrations.AddField(
            model_name='paymentmethod',
            name='paymob_token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_holder_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='expiration_date',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        # 4. Remove old field
        migrations.RemoveField(
            model_name='paymentmethod',
            name='last_four_digits',
        ),
        # 5. Apply new constraint
        migrations.AlterUniqueTogether(
            name='paymentmethod',
            unique_together={('user', 'masked_pan', 'card_type')},
        ),
    ]
