from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views

app_name = 'orders'

# Create a router and register viewsets that will use it.
router = DefaultRouter()
router.register(r'projectoffers', views.ProjectOfferViewset, basename='projectoffer')
router.register(r'worker-tasks', views.WorkerTasksViewSet, basename='worker-task')

urlpatterns = [
    # Explicit URLs for OrderViewSet (standard actions)
    path('', views.OrderViewSet.as_view({'get': 'list', 'post': 'create'}), name='order-list'),
    path('<int:order_id>/', views.OrderViewSet.as_view({'get': 'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'}), name='order-detail'),
    path('available-for-offer/', views.OrderViewSet.as_view({'get': 'available_for_offer'}), name='order-available-for-offer'),
    path('<int:order_id>/offers/', views.OrderViewSet.as_view({'get': 'offers'}), name='order-offers'),

    # Explicit URLs for OrderViewSet custom actions (order_id-specific)
    path('<int:order_id>/accept-offer/<int:offer_id>/',
         views.OrderViewSet.as_view({'post': 'accept_offer'}),
         name='order-accept-offer'),
    path('<int:order_id>/decline-offer/<int:offer_id>/',
         views.OrderViewSet.as_view({'post': 'decline_offer'}),
         name='order-decline-offer'),
    path('<int:order_id>/mark-job-done/',
         views.OrderViewSet.as_view({'post': 'mark_job_done'}),
         name='order-mark-job-done'),
    path('<int:order_id>/release-funds/',
         views.OrderViewSet.as_view({'post': 'release_funds'}),
         name='order-release-funds'),
    path('<int:order_id>/initiate-dispute/',
         views.OrderViewSet.as_view({'post': 'initiate_dispute'}),
         name='order-initiate-dispute'),
    path('<int:order_id>/cancel-order/',
         views.OrderViewSet.as_view({'post': 'cancel_order'}),
         name='order-cancel-order'),

    # Include router URLs for ProjectOfferViewset and WorkerTasksViewSet
    path('', include(router.urls)), # This should be at the end to avoid conflicts

    # Custom action URLs for ProjectOfferViewset that are not automatically generated by DefaultRouter
    # These paths are intentionally after the general router include to ensure they don't get overwritten
    path('projectoffers/client-offers-for-technician/',
         views.ProjectOfferViewset.as_view({'get': 'client_offers_for_technician'}),
         name='projectoffer-client-offers-for-technician'),
    path('projectoffers/<int:offer_id>/update-client-offer/',
         views.ProjectOfferViewset.as_view({'put': 'update_client_offer', 'patch': 'update_client_offer'}),
         name='projectoffer-update-client-offer'),
]
