# Generated by Django 5.2.1 on 2025-12-02 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_order_auto_release_date_order_job_done_timestamp_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('dispute_id', models.AutoField(primary_key=True, serialize=False)),
                ('initiated_date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('resolution', models.CharField(blank=True, choices=[('refund_client', 'Refund Client'), ('release_technician', 'Release Funds to Technician'), ('split_funds', 'Split Funds'), ('other', 'Other')], max_length=50, null=True)),
                ('resolution_details', models.TextField(blank=True, null=True)),
                ('resolution_date', models.DateTimeField(blank=True, null=True)),
                ('resolved_amount_to_client', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('resolved_amount_to_technician', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('admin_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_disputes', to=settings.AUTH_USER_MODEL)),
                ('client_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_disputes', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='orders.order')),
                ('technician_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='involved_disputes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'DISPUTE',
            },
        ),
    ]
