# Generated by Django 5.2.1 on 2025-12-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispute',
            old_name='resolution_details',
            new_name='admin_notes',
        ),
        migrations.RenameField(
            model_name='dispute',
            old_name='initiated_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='dispute',
            old_name='client_user',
            new_name='initiator',
        ),
        migrations.RemoveField(
            model_name='dispute',
            name='admin_reviewer',
        ),
        migrations.RemoveField(
            model_name='dispute',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='dispute',
            name='resolved_amount_to_client',
        ),
        migrations.RemoveField(
            model_name='dispute',
            name='resolved_amount_to_technician',
        ),
        migrations.RemoveField(
            model_name='dispute',
            name='technician_user',
        ),
        migrations.AddField(
            model_name='dispute',
            name='client_argument',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispute',
            name='technician_argument',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='resolution',
            field=models.CharField(blank=True, choices=[('PAY_TECHNICIAN', 'Pay Technician'), ('REFUND_CLIENT', 'Refund Client'), ('SPLIT_PAYMENT', 'Split Payment')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_REVIEW', 'In Review'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=20),
        ),
    ]
