# Generated by Django 5.2.1 on 2025-12-11 01:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0002_rename_resolution_details_dispute_admin_notes_and_more'),
        ('orders', '0005_order_expected_price_alter_order_order_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['order', '-created_at'], name='DISPUTE_order_i_864f32_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['status', '-created_at'], name='DISPUTE_status_d87968_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['initiator', '-created_at'], name='DISPUTE_initiat_26417a_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['order', 'status'], name='DISPUTE_order_i_2e1b34_idx'),
        ),
    ]
