# Generated by Django 5.2.1 on 2025-12-11 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0003_dispute_dispute_order_i_864f32_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisputeResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_type', models.CharField(choices=[('CLIENT', 'Client'), ('TECHNICIAN', 'Technician'), ('ADMIN', 'Admin')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='disputes.dispute')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispute_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'DISPUTE_RESPONSE',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['dispute', 'created_at'], name='DISPUTE_RES_dispute_26519e_idx'), models.Index(fields=['sender', 'created_at'], name='DISPUTE_RES_sender__1c699d_idx')],
            },
        ),
    ]
