# Generated by Django 5.2.1 on 2025-12-11 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0004_disputeresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='disputeresponse',
            name='file_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
