# Generated by Django 5.2.1 on 2025-12-11 03:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0005_disputeresponse_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disputeresponse',
            name='file_url',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='dispute_response_files'),
        ),
    ]
