# Generated by Django 5.2.1 on 2025-11-17 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='technicianavailability',
            name='technician_user',
        ),
        migrations.AlterUniqueTogether(
            name='technicianskill',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='technicianskill',
            name='service',
        ),
        migrations.RemoveField(
            model_name='technicianskill',
            name='technician_user',
        ),
        migrations.RemoveField(
            model_name='verificationdocument',
            name='technician_user',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='TechnicianAvailability',
        ),
        migrations.DeleteModel(
            name='TechnicianSkill',
        ),
        migrations.DeleteModel(
            name='VerificationDocument',
        ),
    ]
