# Generated by Django 5.2.1 on 2025-11-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_offer_notes_projectoffer_offer_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
