"""
Django settings for srvana project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import sys
import os
import cloudinary
from datetime import timedelta # Import timedelta here for SIMPLE_JWT

# Determine if running in a production environment via an environment variable
IS_PRODUCTION = os.environ.get('DJANGO_PRODUCTION', 'False').lower() == 'true'

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-p6ehu0zote8&-p8$!!kslzx@npy@okh99z+jep9*oa-+7m1!or'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True # DEBUG can remain True for local development without affecting HTTPS redirects now

GOOGLE_OAUTH2_CLIENT_ID = "268062404120-nfkt7hf22qe38i8kerp11ju3s22ut4j1.apps.googleusercontent.com"

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api',
    'users',
    'services',
    'orders',
    'chat',
    'technicians',
    'addresses',
    'payments',
    'notifications',
     'reviews',
     'issue_reports',
     'transactions',
     'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders', # Add corsheaders
    'drf_yasg', # Added for API documentation
    'filesupload', # New app for file uploads
]

# Cloudinary Configuration
cloudinary.config(
    cloud_name=os.environ.get('CLOUDINARY_CLOUD_NAME', 'dpcqmcm0x'),
    api_key=os.environ.get('CLOUDINARY_API_KEY', '191518645279549'),
    api_secret=os.environ.get('CLOUDINARY_API_SECRET', '6jEyD8-FFh0cLiWjJOV059R9Xl4')
)

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication', # Added for DRF browsable API login persistence
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ),
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ),
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema',
    'ATOMIC_REQUESTS': True, # Ensures database transactions are atomic for each request
}

# Base Swagger settings. Scheme and host will be inferred from the request.
SWAGGER_SETTINGS = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
        }
    },
    'USE_SESSION_AUTH': False,
    'DOC_EXPANSION': 'list',  # Set to 'full' for expanded UI
    'APIS_SORTER': 'alpha',
    'OPERATIONS_SORTER': 'alpha',
    'JSON_EDITOR': True,
    'SHOW_REQUEST_HEADERS': True,
    'SUPPORTED_SUBMIT_METHODS': ['get', 'post', 'put', 'delete', 'patch'],
    'VALIDATOR_URL': None,
}

if IS_PRODUCTION:
    # Production-specific settings for HTTPS
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    USE_X_FORWARDED_HOST = True
    SECURE_SSL_REDIRECT = True # Force HTTPS redirects in production
    API_DOMAIN = 'https://srvanaback-268062404120.europe-west1.run.app'
    SWAGGER_SETTINGS['DEFAULT_API_URL'] = API_DOMAIN
    SWAGGER_SETTINGS['SCHEMES'] = ['https']
else:
    # Local development settings for HTTP
    SECURE_PROXY_SSL_HEADER = None
    USE_X_FORWARDED_HOST = False
    SECURE_SSL_REDIRECT = False
    API_DOMAIN = 'http://127.0.0.1:8000'
    SWAGGER_SETTINGS['DEFAULT_API_URL'] = API_DOMAIN
    SWAGGER_SETTINGS['SCHEMES'] = ['http', 'https'] # Allow both for local development, with http as primary


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=365), # Set to a very long duration
    'REFRESH_TOKEN_LIFETIME': timedelta(days=365), # Set to a very long duration
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'user_id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware', # Add CorsMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000", # Allow React frontend to access the API
    "http://localhost:5173", # Allow React frontend to access the API
    "http://localhost:8000", # Default Django runserver port
    "http://127.0.0.1:3000",
    "http://127.0.0.1:5173",
    "http://127.0.0.1:8000",
    "http://99zarka.github.io",
    "https://99zarka.github.io",
    "http://www.srvana.tech",
    "https://www.srvana.tech",
    "http://srvanaback-268062404120.europe-west1.run.app",
    "https://srvanaback-268062404120.europe-west1.run.app" # The backend's own URL might need to be allowed
]

# If you want to allow all origins during development, you can use:
# CORS_ALLOW_ALL_ORIGINS = True # Temporarily allow all origins for local file testing

# WARNING: Allowing all origins for CSRF is generally not recommended for production due to security risks.
# It is used here for development/testing purposes as per user request.
# WARNING: Allowing all origins for CSRF is generally not recommended for production due to security risks.
# It is used here for development/testing purposes as per user request.
CSRF_TRUSTED_ORIGINS = ['https://*', 'http://*', 'https://srvanaback-268062404120.europe-west1.run.app']

ROOT_URLCONF = 'srvana.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'srvana.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Local SQLite database (commented out for production)
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
    # }
# }

# Cloud PostgreSQL database configuration
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'defaultdb',
        'USER': 'avnadmin',
        'PASSWORD': 'AVNS_5Z_eP5ZxbwMflRkUbSn',
        'HOST': 'srvana-mohamedmanchestrawy-test.f.aivencloud.com',
        'PORT': '15292',
        'OPTIONS': {
            'sslmode': 'require',
        },
        'CONN_MAX_AGE': 600,
    }
}

# if 'test' in sys.argv:
#     DATABASES['default'] = {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'test_db.sqlite3',
#     }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'users.User'
