# Generated by Django 5.2.1 on 2025-11-16 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'SERVICE_CATEGORY',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('service_type', models.CharField(max_length=255)),
                ('base_inspection_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_price_range_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_price_range_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('emergency_surcharge_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.servicecategory')),
            ],
            options={
                'db_table': 'SERVICE',
            },
        ),
    ]
