# Generated by Django 5.2.1 on 2025-12-03 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_servicecategory_icon_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='arabic_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='arabic_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
