# Generated by Django 5.2.1 on 2025-12-13 18:25

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='message',
            name='file_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='file_url',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='chat_files'),
        ),
        migrations.AddField(
            model_name='message',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'timestamp'], name='MESSAGE_convers_409672_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender'], name='MESSAGE_sender__babf56_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'is_read'], name='MESSAGE_convers_ca75a9_idx'),
        ),
        migrations.AlterModelTable(
            name='message',
            table='MESSAGE',
        ),
    ]
