# Generated by Django 5.2.1 on 2025-12-20 06:27

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_aiconversation_aiconversationmessage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconversationmessage',
            name='file_url',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='chat_files'),
        ),
        migrations.AddField(
            model_name='aiconversationmessage',
            name='image_url',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='chat_images'),
        ),
        migrations.AlterField(
            model_name='aiconversation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
