# Generated by Django 5.2.1 on 2025-12-02 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0001_initial'),
        ('transactions', '0002_transaction_related_user_alter_transaction_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='dispute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='disputes.dispute'),
        ),
    ]
