# Generated by Django 5.2.1 on 2025-12-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_rename_created_at_transaction_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('ESCROW_HOLD', 'Escrow Hold'), ('ESCROW_RELEASE', 'Escrow Release'), ('CANCEL_REFUND', 'Cancel Refund'), ('DISPUTE_PAYOUT', 'Dispute Payout'), ('DISPUTE_REFUND', 'Dispute Refund'), ('FEE', 'Fee'), ('PENDING_TO_AVAILABLE_TRANSFER', 'Pending To Available Transfer')], max_length=50),
        ),
    ]
