# Generated by Django 5.2.1 on 2025-12-19 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_transaction_transaction_type'),
        ('transactions', '0006_alter_transaction_transaction_type'),
    ]

    operations = [
    ]
