# Generated by Django 5.2.1 on 2025-12-20 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_merge_20251219_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('ESCROW_HOLD', 'Escrow Hold'), ('ESCROW_RELEASE', 'Escrow Release'), ('CANCEL_REFUND', 'Cancel Refund'), ('DISPUTE_PAYOUT', 'Dispute Payout'), ('DISPUTE_REFUND', 'Dispute Refund'), ('FEE', 'Fee'), ('PENDING_TO_AVAILABLE_TRANSFER', 'Pending To Available Transfer'), ('PLATFORM_FEE', 'Platform Fee'), ('PAYOUT', 'Payout')], max_length=50),
        ),
    ]
