# Generated by Django 5.2.1 on 2025-12-12 08:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_order_status_and_more'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['order'], name='reviews_rev_order_i_a8ba91_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['order', 'rating'], name='reviews_rev_order_i_819abf_idx'),
        ),
    ]
