# Generated by Django 5.2.1 on 2025-11-16 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_type', models.CharField(max_length=255)),
                ('problem_description', models.TextField()),
                ('requested_location', models.TextField()),
                ('scheduled_date', models.DateField()),
                ('scheduled_time_start', models.CharField(max_length=255)),
                ('scheduled_time_end', models.CharField(max_length=255)),
                ('order_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('on_hold', 'On Hold'), ('awaiting_payment', 'Awaiting Payment'), ('disputed', 'Disputed')], default='pending', max_length=20)),
                ('initial_observations', models.TextField(blank=True, null=True)),
                ('updated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('updated_schedule_date', models.DateField(blank=True, null=True)),
                ('updated_schedule_time_start', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_schedule_time_end', models.CharField(blank=True, max_length=255, null=True)),
                ('proposal_notes', models.TextField(blank=True, null=True)),
                ('creation_timestamp', models.DateField()),
                ('job_start_timestamp', models.DateField(blank=True, null=True)),
                ('job_completion_timestamp', models.DateField(blank=True, null=True)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('commission_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('platform_commission_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('service_fee_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('service_fee_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_amount_paid_by_client', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount_to_technician', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('client_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_orders', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
                ('technician_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technician_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ORDER',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('media_id', models.AutoField(primary_key=True, serialize=False)),
                ('media_url', models.CharField(max_length=255)),
                ('media_type', models.CharField(max_length=255)),
                ('upload_date', models.DateField()),
                ('context', models.TextField(blank=True, null=True)),
                ('client_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_media', to=settings.AUTH_USER_MODEL)),
                ('technician_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technician_media', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
            options={
                'db_table': 'MEDIA',
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('complaint_details', models.TextField()),
                ('submission_date', models.DateField()),
                ('status', models.CharField(max_length=255)),
                ('resolution_details', models.TextField(blank=True, null=True)),
                ('resolution_date', models.DateField(blank=True, null=True)),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_complaints', to=settings.AUTH_USER_MODEL)),
                ('client_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_complaints', to=settings.AUTH_USER_MODEL)),
                ('technician_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technician_complaints', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
            options={
                'db_table': 'COMPLAINT',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_method', models.CharField(max_length=255)),
                ('transaction_id', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('payment_status', models.CharField(max_length=255)),
                ('is_deposit', models.BooleanField()),
                ('client_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_payments', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
            options={
                'db_table': 'PAYMENT',
            },
        ),
        migrations.CreateModel(
            name='ProjectOffer',
            fields=[
                ('offer_id', models.AutoField(primary_key=True, serialize=False)),
                ('offered_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offer_description', models.TextField(blank=True, null=True)),
                ('offer_date', models.DateField()),
                ('status', models.CharField(max_length=255)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_offers', to='orders.order')),
                ('technician_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PROJECT_OFFER',
            },
        ),
    ]
