# Generated by Django 5.2.1 on 2025-11-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectoffer',
            name='offer_initiator',
            field=models.CharField(choices=[('client', 'Client'), ('technician', 'Technician')], default='technician', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('awaiting_technician_response', 'Awaiting Technician Response'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('on_hold', 'On Hold'), ('awaiting_payment', 'Awaiting Payment'), ('disputed', 'Disputed')], default='pending', max_length=50),
        ),
    ]
