# Generated by Django 5.2.1 on 2025-12-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_auto_release_date_order_job_done_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('ACCEPTED', 'Accepted'), ('IN_PROGRESS', 'In Progress'), ('AWAITING_RELEASE', 'Awaiting Release'), ('COMPLETED', 'Completed'), ('DISPUTED', 'Disputed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='OPEN', max_length=50),
        ),
    ]
