# Generated by Django 5.2.1 on 2025-12-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expected_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('ACCEPTED', 'Accepted'), ('IN_PROGRESS', 'In Progress'), ('AWAITING_RELEASE', 'Awaiting Release'), ('COMPLETED', 'Completed'), ('DISPUTED', 'Disputed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded'), ('AWAITING_TECHNICIAN_RESPONSE', 'Awaiting Technician Response')], default='OPEN', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('direct_hire', 'Direct Hire'), ('service_request', 'Service Request')], max_length=255),
        ),
    ]
