# Generated by Django 5.2.1 on 2025-12-11 01:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_expected_price_alter_order_order_status_and_more'),
        ('services', '0003_service_arabic_name_servicecategory_arabic_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('ACCEPTED', 'Accepted'), ('IN_PROGRESS', 'In Progress'), ('AWAITING_RELEASE', 'Awaiting Release'), ('COMPLETED', 'Completed'), ('DISPUTED', 'Disputed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded'), ('AWAITING_TECHNICIAN_RESPONSE', 'Awaiting Technician Response'), ('AWAITING_CLIENT_ESCROW_CONFIRMATION', 'Awaiting Client Escrow Confirmation')], default='OPEN', max_length=50),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['client_user', '-order_id'], name='ORDER_client__8f0be8_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['technician_user', '-order_id'], name='ORDER_technic_30430a_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_status', '-order_id'], name='ORDER_order_s_a82887_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['creation_timestamp', '-order_id'], name='ORDER_creatio_40a451_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['client_user', 'order_status', '-order_id'], name='ORDER_client__16ab9d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['technician_user', 'order_status', '-order_id'], name='ORDER_technic_564278_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_id'], name='ORDER_order_i_0ba98d_idx'),
        ),
        migrations.AddIndex(
            model_name='projectoffer',
            index=models.Index(fields=['order', 'status'], name='PROJECT_OFF_order_i_d94b5f_idx'),
        ),
        migrations.AddIndex(
            model_name='projectoffer',
            index=models.Index(fields=['technician_user', 'status'], name='PROJECT_OFF_technic_60ef06_idx'),
        ),
        migrations.AddIndex(
            model_name='projectoffer',
            index=models.Index(fields=['order', 'offer_initiator', 'status'], name='PROJECT_OFF_order_i_1dcbe6_idx'),
        ),
        migrations.AddIndex(
            model_name='projectoffer',
            index=models.Index(fields=['offer_date', '-offer_id'], name='PROJECT_OFF_offer_d_03b2ef_idx'),
        ),
    ]
