# Generated by Django 5.2.1 on 2025-11-30 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_rename_recipient_to_user'),
        ('orders', '0002_projectoffer_offer_initiator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.projectoffer'),
        ),
    ]
