# Generated by Django 5.2.1 on 2025-12-07 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0002_rename_resolution_details_dispute_admin_notes_and_more'),
        ('notifications', '0003_notification_related_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_dispute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disputes.dispute'),
        ),
    ]
